# Generated by Django 4.1.7 on 2023-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ("last_name",),
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ("title", "author__last_name"),
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AddField(
            model_name="reader",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Отчество"
            ),
        ),
    ]
