# Generated by Django 4.1.7 on 2023-02-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "author")},
        ),
    ]
